
package service63;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service63", targetNamespace = "http://service63/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service63 {


    /**
     * 
     * @param setMarkMark
     */
    @WebMethod
    @Action(input = "http://service63/Service63/setMarkRequest", output = "http://service63/Service63/setMarkResponse")
    public void setMark(
        @WebParam(name = "setMarkMark", partName = "setMarkMark")
        double setMarkMark);

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "getAcademicYear", partName = "getAcademicYear")
    @Action(input = "http://service63/Service63/getAcademicYearRequest", output = "http://service63/Service63/getAcademicYearResponse")
    public double getAcademicYear();

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "getModuleCode", partName = "getModuleCode")
    @Action(input = "http://service63/Service63/getModuleCodeRequest", output = "http://service63/Service63/getModuleCodeResponse")
    public double getModuleCode();

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "getMarkResult", partName = "getMarkResult")
    @Action(input = "http://service63/Service63/getMarkRequest", output = "http://service63/Service63/getMarkResponse")
    public double getMark();

    /**
     * 
     * @return
     *     returns service63.AcademicStaffMemberArray
     */
    @WebMethod
    @WebResult(name = "getAcademicStaffMembersResult", partName = "getAcademicStaffMembersResult")
    @Action(input = "http://service63/Service63/getAsmsRequest", output = "http://service63/Service63/getAsmsResponse")
    public AcademicStaffMemberArray getAsms();

    /**
     * 
     * @param addToArrayAcademicStaffMember
     */
    @WebMethod
    @Action(input = "http://service63/Service63/addToArrayRequest", output = "http://service63/Service63/addToArrayResponse")
    public void addToArray(
        @WebParam(name = "addToArrayAcademicStaffMember", partName = "addToArrayAcademicStaffMember")
        AcademicStaffMember addToArrayAcademicStaffMember);

    /**
     * 
     * @param moduleCode
     * @param academicStaffMember
     * @param academicStaffMembers
     * @param module
     * @throws FileNotFoundException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod(operationName = "Servi\u00e7e22")
    @Action(input = "http://service63/Service63/Servi\u00e7e22Request", output = "http://service63/Service63/Servi\u00e7e22Response", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://service63/Service63/Servi\u00e7e22/Fault/FileNotFoundException"),
        @FaultAction(className = JAXBException_Exception.class, value = "http://service63/Service63/Servi\u00e7e22/Fault/JAXBException")
    })
    public void serviçe22(
        @WebParam(name = "AcademicStaffMember", partName = "AcademicStaffMember")
        AcademicStaffMember academicStaffMember,
        @WebParam(name = "AcademicStaffMembers", partName = "AcademicStaffMembers")
        AcademicStaffMembers academicStaffMembers,
        @WebParam(name = "Module", partName = "Module")
        Module63 module,
        @WebParam(name = "ModuleCode", partName = "ModuleCode")
        ModuleCode63 moduleCode)
        throws FileNotFoundException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param moduleModuleCode
     * @param moduleAcademicYear
     */
    @WebMethod(operationName = "Module")
    @Action(input = "http://service63/Service63/ModuleRequest", output = "http://service63/Service63/ModuleResponse")
    public void module(
        @WebParam(name = "ModuleModuleCode", partName = "ModuleModuleCode")
        ModuleCode63 moduleModuleCode,
        @WebParam(name = "ModuleAcademicYear", partName = "ModuleAcademicYear")
        String moduleAcademicYear);

    /**
     * 
     * @param getAcademicStaffMemberID
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "getAcademicStaffMemberIDResult", partName = "getAcademicStaffMemberIDResult")
    @Action(input = "http://service63/Service63/getAsmIDRequest", output = "http://service63/Service63/getAsmIDResponse")
    public int getAsmID(
        @WebParam(name = "getAcademicStaffMemberID", partName = "getAcademicStaffMemberID")
        int getAcademicStaffMemberID);

    /**
     * 
     * @param addToModulesModule
     * @param addToModulesModuleCode
     */
    @WebMethod
    @Action(input = "http://service63/Service63/addToModulesRequest", output = "http://service63/Service63/addToModulesResponse")
    public void addToModules(
        @WebParam(name = "addToModulesModule", partName = "addToModulesModule")
        Module63 addToModulesModule,
        @WebParam(name = "addToModulesModuleCode", partName = "addToModulesModuleCode")
        ModuleCode63 addToModulesModuleCode);

    /**
     * 
     * @return
     *     returns service63.Module63Array
     */
    @WebMethod
    @WebResult(name = "getModulesResult", partName = "getModulesResult")
    @Action(input = "http://service63/Service63/getModulesRequest", output = "http://service63/Service63/getModulesResponse")
    public Module63Array getModules();

    /**
     * 
     * @param academicStaffMemberID
     */
    @WebMethod(operationName = "AcademicStaffMember")
    @Action(input = "http://service63/Service63/AcademicStaffMemberRequest", output = "http://service63/Service63/AcademicStaffMemberResponse")
    public void academicStaffMember(
        @WebParam(name = "AcademicStaffMemberID", partName = "AcademicStaffMemberID")
        int academicStaffMemberID);

}
