
package service63;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service63ImplService", targetNamespace = "http://service63/", wsdlLocation = "http://localhost:8080/Service63/?wsdl")
public class Service63ImplService
    extends Service
{

    private final static URL SERVICE63IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE63IMPLSERVICE_EXCEPTION;
    private final static QName SERVICE63IMPLSERVICE_QNAME = new QName("http://service63/", "Service63ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Service63/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE63IMPLSERVICE_WSDL_LOCATION = url;
        SERVICE63IMPLSERVICE_EXCEPTION = e;
    }

    public Service63ImplService() {
        super(__getWsdlLocation(), SERVICE63IMPLSERVICE_QNAME);
    }

    public Service63ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE63IMPLSERVICE_QNAME, features);
    }

    public Service63ImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE63IMPLSERVICE_QNAME);
    }

    public Service63ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE63IMPLSERVICE_QNAME, features);
    }

    public Service63ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service63ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Service63
     */
    @WebEndpoint(name = "Service63ImplPort")
    public Service63 getService63ImplPort() {
        return super.getPort(new QName("http://service63/", "Service63ImplPort"), Service63.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service63
     */
    @WebEndpoint(name = "Service63ImplPort")
    public Service63 getService63ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service63/", "Service63ImplPort"), Service63.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE63IMPLSERVICE_EXCEPTION!= null) {
            throw SERVICE63IMPLSERVICE_EXCEPTION;
        }
        return SERVICE63IMPLSERVICE_WSDL_LOCATION;
    }

}
