
package service9;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service9ImplService", targetNamespace = "http://service9/", wsdlLocation = "http://localhost:8080/Service9/?wsdl")
public class Service9ImplService
    extends Service
{

    private final static URL SERVICE9IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE9IMPLSERVICE_EXCEPTION;
    private final static QName SERVICE9IMPLSERVICE_QNAME = new QName("http://service9/", "Service9ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Service9/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE9IMPLSERVICE_WSDL_LOCATION = url;
        SERVICE9IMPLSERVICE_EXCEPTION = e;
    }

    public Service9ImplService() {
        super(__getWsdlLocation(), SERVICE9IMPLSERVICE_QNAME);
    }

    public Service9ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE9IMPLSERVICE_QNAME, features);
    }

    public Service9ImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE9IMPLSERVICE_QNAME);
    }

    public Service9ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE9IMPLSERVICE_QNAME, features);
    }

    public Service9ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service9ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Service9
     */
    @WebEndpoint(name = "Service9ImplPort")
    public Service9 getService9ImplPort() {
        return super.getPort(new QName("http://service9/", "Service9ImplPort"), Service9.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service9
     */
    @WebEndpoint(name = "Service9ImplPort")
    public Service9 getService9ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service9/", "Service9ImplPort"), Service9.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE9IMPLSERVICE_EXCEPTION!= null) {
            throw SERVICE9IMPLSERVICE_EXCEPTION;
        }
        return SERVICE9IMPLSERVICE_WSDL_LOCATION;
    }

}
