
package service22;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service22ImplService", targetNamespace = "http://service22/", wsdlLocation = "http://localhost:8080/Service22/?wsdl")
public class Service22ImplService
    extends Service
{

    private final static URL SERVICE22IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE22IMPLSERVICE_EXCEPTION;
    private final static QName SERVICE22IMPLSERVICE_QNAME = new QName("http://service22/", "Service22ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Service22/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE22IMPLSERVICE_WSDL_LOCATION = url;
        SERVICE22IMPLSERVICE_EXCEPTION = e;
    }

    public Service22ImplService() {
        super(__getWsdlLocation(), SERVICE22IMPLSERVICE_QNAME);
    }

    public Service22ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE22IMPLSERVICE_QNAME, features);
    }

    public Service22ImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE22IMPLSERVICE_QNAME);
    }

    public Service22ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE22IMPLSERVICE_QNAME, features);
    }

    public Service22ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service22ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Service22
     */
    @WebEndpoint(name = "Service22ImplPort")
    public Service22 getService22ImplPort() {
        return super.getPort(new QName("http://service22/", "Service22ImplPort"), Service22.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service22
     */
    @WebEndpoint(name = "Service22ImplPort")
    public Service22 getService22ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service22/", "Service22ImplPort"), Service22.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE22IMPLSERVICE_EXCEPTION!= null) {
            throw SERVICE22IMPLSERVICE_EXCEPTION;
        }
        return SERVICE22IMPLSERVICE_WSDL_LOCATION;
    }

}
